openapi: 3.0.0
info:
  title: 'Notebook API'
  version: 1.0.0
paths:
  /notebook:
    get:
      summary: 'Get all notebooks'
      operationId: d08559fcae8b9b6b25747533ba924cc6
      responses:
        '200':
          description: 'Notebooks data'
    post:
      summary: 'Create a new notebook'
      operationId: 09b50604f54eea208de3bb489cdc2a95
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notebook'
      responses:
        '201':
          description: 'Created notebook'
        '409':
          description: 'Notebook with this fio, email, or phone already exists'
  '/notebook/{id}':
    get:
      summary: 'Get a notebook by ID'
      operationId: ca8fa3795c051aa82157b27982d8f7ce
      parameters:
        -
          name: id
          in: path
          description: 'ID of the notebook'
      responses:
        '200':
          description: Notebook
        '404':
          description: 'Notebook not found'
    put:
      summary: 'Update a notebook by ID'
      operationId: 9c63754f7ecf02301842f654cc77c3a9
      parameters:
        -
          name: id
          in: path
          description: 'ID of the notebook'
      responses:
        '200':
          description: 'Notebook updated'
        '404':
          description: 'Notebook not found'
    delete:
      summary: 'Delete a notebook by ID'
      operationId: d120841256f16aec86b6b8a982731e8f
      parameters:
        -
          name: id
          in: path
          description: 'ID of the notebook'
      responses:
        '200':
          description: 'Delete success'
        '404':
          description: 'Notebook not found'
